policy_path: "policy_29dof.pt"

# kps: [
#     100.0, 100.0, 100.0, 150.0, 40.0, 40.0,  # left leg
#     100.0, 100.0, 100.0, 150.0, 40.0, 40.0,  # right leg
#     200.0, 200.0, 200.0,                    
#     40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0,    
#     40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0
# ]

# kds: [
#     2.0, 2.0, 2.0, 4.0, 2.0, 2.0,          # left leg
#     2.0, 2.0, 2.0, 4.0, 2.0, 2.0,          # right leg
#     5.0, 5.0, 5.0,                         # waist
#     10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,    # left arm
#     10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0     # right arm
# ]

    # 'left_hip_pitch_joint',
    # 'left_hip_roll_joint',
    # 'left_hip_yaw_joint',
    # 'left_knee_joint',
    # 'left_ankle_pitch_joint',
    # 'left_ankle_roll_joint',

    # 'right_hip_pitch_joint',
    # 'right_hip_roll_joint',
    # 'right_hip_yaw_joint',
    # 'right_knee_joint',
    # 'right_ankle_pitch_joint',
    # 'right_ankle_roll_joint',

    # 'waist_yaw_joint',
    # 'waist_roll_joint',
    # 'waist_pitch_joint',

    # 'left_shoulder_pitch_joint',
    # 'left_shoulder_roll_joint',
    # 'left_shoulder_yaw_joint',
    # 'left_elbow_joint',
    # 'left_wrist_roll_joint',
    # 'left_wrist_pitch_joint',
    # 'left_wrist_yaw_joint',

    # 'right_shoulder_pitch_joint',
    # 'right_shoulder_roll_joint',
    # 'right_shoulder_yaw_joint',
    # 'right_elbow_joint',
    # 'right_wrist_roll_joint',
    # 'right_wrist_pitch_joint',
    # 'right_wrist_yaw_joint'

kps: [
    100, 100, 100, 150, 40, 40,  # left leg
    100, 100, 100, 150, 40, 40,  # right leg
    200, 40, 40,                    
    40, 40, 40, 40, 40, 40, 40,    
    40, 40, 40, 40, 40, 40, 40
]

kds: [
    2, 2, 2, 4, 2, 2,          # left leg
    2, 2, 2, 4, 2, 2,          # right leg
    5, 5, 5,                         # waist
    1, 1, 1, 1, 1, 1, 1,    # left arm
    1, 1, 1, 1, 1, 1, 1     # right arm
]

tau_limit: [
    88, 139, 88, 139, 25, 25,            # left leg
    88, 139, 88, 139, 25, 25,            # right leg
    88, 25, 25,                         # waist
    25, 25, 25, 25, 25, 5, 5,         # left arm
    25, 25, 25, 25, 25, 5, 5         # right arm
]

default_angles: [
      -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,                                  
      -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,          
       0.0, 0.0, 0.0,         
       0.3, 0.25, 0.0, 0.97, 0.15, 0.0,0.0,            
       0.3, -0.25, 0.0,0.97, -0.15, 0.0,0.0                          
]

velocity_limit: [
    32, 20, 32, 20, 37, 37,          # left leg
    32, 20, 32, 20, 37, 37,          # right leg
    32, 37, 37,                         # waist
    37, 37, 37, 37, 37, 22, 22,    # left arm
    37, 37, 37, 37, 37, 22, 22     # right arm
]

dof29_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,19,20,21,
               22, 23, 24, 25,26,27,28
]

cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0, 0, 0]
ang_vel_scale: 1
dof_pos_scale: 1
dof_vel_scale: 1

action_scale: 0.25
num_actions: 29

num_obs: 1020

cmd_range: {lin_vel_x: [-0.6, 1.0], lin_vel_y: [-0.5, 0.5], ang_vel_z: [-1.57, 1.57]}



